#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

# Update system and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Backup the original haproxy.cfg
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Clean haproxy.cfg (optional)
# sudo truncate -s 0 /etc/haproxy/haproxy.cfg

# Check if the configuration for frontend and backend exists
if ! grep -q "frontend alliane-frontend" /etc/haproxy/haproxy.cfg; then
    # Add frontend and backend configuration
    server_config="frontend alliane-frontend
        bind *:80
        mode http
        default_backend alliane-backend

    backend alliane-backend
        balance roundrobin
        server web-01 18.212.63.12:80 check
        server web-02 44.211.248.36:80 check"

    # Append the configuration to haproxy.cfg
    echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
else
    echo "Frontend and Backend configuration already exists in haproxy.cfg."
fi

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
