#!/usr/bin/env bash
# Configure Nginx with custom HTTP header

# Update and install Nginx
sudo apt update -y
sudo apt install nginx -y

# Get the hostname
HOSTNAME=$(hostname)

# Add header to Nginx configuration
sudo sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# If the test is successful, restart Nginx
if [ $? -eq 0 ]; then
    sudo systemctl restart nginx
    echo "Nginx configuration updated and restarted successfully."
else
    echo "Nginx configuration test failed. Please check the configuration."
    exit 1
fi
